# Generated by Django 5.0.6 on 2024-05-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedrigoni', '0005_alter_pdf_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdf',
            name='archivo',
            field=models.FileField(upload_to='pdfs/'),
        ),
    ]
