# Generated by Django 5.0.6 on 2024-05-29 20:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fedrigoni', '0006_alter_pdf_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
