# Generated by Django 5.0.6 on 2024-05-29 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fedrigoni', '0007_pdf_upload_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdf',
            name='upload_date',
        ),
    ]
