# Generated by Django 5.0.6 on 2024-05-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maquina',
            name='nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
