# Generated by Django 5.0.6 on 2024-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0002_maquina_descripcion_alter_maquina_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='pdf',
            field=models.BinaryField(default=b'\x08', max_length=10),
        ),
    ]
