# Generated by Django 5.0.6 on 2024-05-31 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maquinas', '0004_alter_maquina_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquina',
            name='titulo',
            field=models.CharField(default=4, max_length=150),
            preserve_default=False,
        ),
    ]
